name: AI Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  ai-review:
    name: AI Code Review
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Review
        uses: Nikita-Filonov/ai-review@v0.56.0
        with:
          review-command: run
        env:
          LLM__PROVIDER: "OPENAI"
          LLM__META__MODEL: ${{ vars.AI_REVIEW_MODEL }}
          LLM__META__MAX_TOKENS: "15000"
          LLM__META__TEMPERATURE: "0.3"
          LLM__HTTP_CLIENT__API_URL: "https://api.openai.com/v1"
          LLM__HTTP_CLIENT__API_TOKEN: ${{ secrets.OPENAI_API_KEY }}
          VCS__PROVIDER: "GITEA"
          VCS__PIPELINE__OWNER: ${{ github.repository_owner }}
          VCS__PIPELINE__REPO: ${{ github.event.repository.name }}
          VCS__PIPELINE__PULL_NUMBER: ${{ github.event.pull_request.number }}
          VCS__HTTP_CLIENT__API_URL: ${{ github.server_url }}/api/v1
          VCS__HTTP_CLIENT__API_TOKEN: ${{ secrets.AI_REVIEW_GITEA_TOKEN }}
